version: '3.8'
services:
  server:
    build: .
    restart: always
#    env_file: ./.env
    ports:
      - "9000:3000"
      - "3306:3306"
    volumes:
      - ./src:/sales-tray-backend/src
    stdin_open: true
    tty: true
